"use client";

import Link from "next/link";
import { Minus, Plus, Trash2 } from "lucide-react";
import { useCart } from "@/components/CartProvider";

export default function CartPage() {
  const { items, subtotal, updateQuantity, removeItem } = useCart();
  const shipping = subtotal >= 999 || subtotal === 0 ? 0 : 99;
  if (!items.length) return <main className="mx-auto max-w-4xl px-4 py-20"><h1 className="font-display text-5xl text-cocoa">Your Cart</h1><div className="mt-8 rounded-3xl bg-ivory p-12 text-center"><h2 className="font-display text-3xl">Your cart is waiting for something pawsome.</h2><p className="mt-3 text-gray-600">Add your favourite Tobby &amp; Yuki products and they will appear here.</p><Link href="/" className="mt-7 inline-block rounded-full bg-cocoa px-7 py-3 text-sm font-bold text-white">Continue shopping</Link></div></main>;
  return <main className="mx-auto max-w-6xl px-4 py-12"><h1 className="font-display text-5xl text-cocoa">Your Cart</h1><div className="mt-9 grid gap-8 lg:grid-cols-[1.4fr_.6fr]"><section className="space-y-4">{items.map((item) => <article key={`${item.slug}-${item.size}`} className="flex gap-4 rounded-2xl border border-black/5 p-4"><img src={item.image} alt="" className="h-24 w-24 rounded-xl bg-ivory object-cover" /><div className="min-w-0 flex-1"><div className="flex justify-between gap-3"><div><h2 className="font-semibold text-cocoa">{item.name}</h2>{item.size && <p className="mt-1 text-xs text-gray-500">Size: {item.size}</p>}</div><button onClick={() => removeItem(item.slug, item.size)} aria-label={`Remove ${item.name}`} className="text-gray-400 hover:text-rose"><Trash2 size={18} /></button></div><div className="mt-4 flex items-center justify-between"><div className="flex items-center rounded-full border"><button onClick={() => updateQuantity(item.slug, item.size, item.quantity - 1)} className="p-2"><Minus size={15} /></button><span className="w-7 text-center text-sm">{item.quantity}</span><button onClick={() => updateQuantity(item.slug, item.size, item.quantity + 1)} className="p-2"><Plus size={15} /></button></div><p className="font-semibold text-cocoa">₹{(item.price * item.quantity).toLocaleString("en-IN")}</p></div></div></article>)}</section><aside className="h-fit rounded-3xl bg-ivory p-6"><h2 className="font-display text-3xl text-cocoa">Order summary</h2><div className="mt-6 space-y-3 text-sm text-gray-600"><p className="flex justify-between"><span>Subtotal</span><span>₹{subtotal.toLocaleString("en-IN")}</span></p><p className="flex justify-between"><span>Shipping</span><span>{shipping ? `₹${shipping}` : "Free"}</span></p><p className="border-t border-black/10 pt-3 text-base font-bold text-cocoa">Total <span className="float-right">₹{(subtotal + shipping).toLocaleString("en-IN")}</span></p></div><Link href="/checkout" className="mt-6 block rounded-full bg-cocoa py-3 text-center text-sm font-bold text-white hover:bg-mocha">Proceed to checkout</Link><p className="mt-4 text-center text-xs text-gray-500">Free shipping on orders above ₹999.</p></aside></div></main>;
}
