"use client";

import { FormEvent, useState } from "react";
import Link from "next/link";
import { CheckCircle2, MapPin } from "lucide-react";
import { useCart } from "@/components/CartProvider";

export default function CheckoutPage() {
  const { items, subtotal } = useCart();
  const [serviceable, setServiceable] = useState<boolean | null>(null);
  const [complete, setComplete] = useState(false);
  const [pincode, setPincode] = useState("");
  const shipping = subtotal >= 999 || subtotal === 0 ? 0 : 99;
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (serviceable) setComplete(true); };
  if (!items.length && !complete) return <main className="mx-auto max-w-4xl px-4 py-20 text-center"><h1 className="font-display text-5xl text-cocoa">Checkout</h1><p className="mt-5 text-gray-600">Your cart is empty.</p><Link href="/" className="mt-7 inline-block rounded-full bg-cocoa px-7 py-3 text-sm font-bold text-white">Continue shopping</Link></main>;
  if (complete) return <main className="mx-auto max-w-xl px-4 py-24 text-center"><CheckCircle2 className="mx-auto text-mocha" size={52} /><h1 className="mt-5 font-display text-5xl text-cocoa">Order received!</h1><p className="mt-4 leading-relaxed text-gray-600">Thank you for choosing Tobby &amp; Yuki. We&apos;ll send your order updates to the email address you provided.</p><Link href="/" className="mt-8 inline-block rounded-full bg-cocoa px-7 py-3 text-sm font-bold text-white">Continue shopping</Link></main>;
  return <main className="mx-auto max-w-6xl px-4 py-12"><h1 className="font-display text-5xl text-cocoa">Checkout</h1><div className="mt-9 grid gap-8 lg:grid-cols-[1.25fr_.75fr]"><form onSubmit={submit} className="space-y-7 rounded-3xl border border-black/5 p-6 shadow-soft"><section><h2 className="font-display text-3xl text-cocoa">Delivery details</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><input required placeholder="First name" className="rounded-xl border p-3 outline-none focus:border-mocha" /><input required placeholder="Last name" className="rounded-xl border p-3 outline-none focus:border-mocha" /><input required type="email" placeholder="Email address" className="rounded-xl border p-3 outline-none focus:border-mocha sm:col-span-2" /><input required placeholder="Address" className="rounded-xl border p-3 outline-none focus:border-mocha sm:col-span-2" /><input required placeholder="City" className="rounded-xl border p-3 outline-none focus:border-mocha" /><div className="flex gap-2"><input required value={pincode} inputMode="numeric" maxLength={6} placeholder="PIN code" className="min-w-0 flex-1 rounded-xl border p-3 outline-none focus:border-mocha" onChange={(e) => { setPincode(e.target.value.replace(/\D/g, "")); setServiceable(null); }} /><button type="button" onClick={() => setServiceable(/^\d{6}$/.test(pincode))} className="rounded-xl bg-ivory px-3 text-sm font-semibold text-cocoa">Check</button></div></div>{serviceable !== null && <p className={`mt-3 flex gap-2 text-sm ${serviceable ? "text-green-700" : "text-rose"}`}><MapPin size={17} />{serviceable ? "Delivery is available to this PIN code." : "Enter a valid 6-digit PIN code to continue."}</p>}</section><section className="border-t border-black/5 pt-7"><h2 className="font-display text-3xl text-cocoa">Payment</h2><label className="mt-4 flex items-center gap-3 rounded-xl border border-cocoa bg-[#f5e9df] p-4 text-sm font-semibold"><input type="radio" defaultChecked name="payment" /> Cash on Delivery</label><label className="mt-3 flex items-center gap-3 rounded-xl border p-4 text-sm"><input type="radio" name="payment" /> Pay securely online (coming soon)</label></section><button disabled={!serviceable} className="w-full rounded-full bg-cocoa py-4 font-bold text-white disabled:cursor-not-allowed disabled:opacity-40">Place order</button></form><aside className="h-fit rounded-3xl bg-ivory p-6"><h2 className="font-display text-3xl text-cocoa">Your order</h2><div className="mt-5 space-y-3">{items.map((item) => <p key={`${item.slug}-${item.size}`} className="flex justify-between gap-3 text-sm text-gray-600"><span>{item.name} × {item.quantity}</span><span>₹{(item.price * item.quantity).toLocaleString("en-IN")}</span></p>)}</div><p className="mt-5 border-t border-black/10 pt-4 font-bold text-cocoa">Total <span className="float-right">₹{(subtotal + shipping).toLocaleString("en-IN")}</span></p></aside></div></main>;
}
